project:
  type: website

website:
  title: "baranickkyra.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: aboutme.qmd
        text: About Me
      - href: interests.qmd
        text: Interests

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual
output-dir: docs


