
project:
  type: website
  output-dir: docs
  resources: 
  - resume.pdf
website:
  title: "Kyra Baranick"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - text: About Me
        menu:
          - href: mosaic.qmd
            text: My Mosaic Art
          - href: hikes.qmd
            text: Favorite Hikes
      - href: interests.qmd
        text: Field/Lab Work

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual



